services:
  homepage:
    build: .
    image: jmllem-portfolio:latest
    container_name: homepage
    restart: always
    ports:
      - "172.17.0.1:3000:80"
    read_only: true
    tmpfs:
      - /var/cache/nginx:rw,noexec,nosuid,size=32m
      - /var/run:rw,noexec,nosuid,size=4m
      - /tmp:rw,noexec,nosuid,size=16m
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - NET_BIND_SERVICE
      - SETGID
      - SETUID
